CREATE OR REPLACE PACKAGE BODY GAME_FLAGS_PQ01 IS

    --jcanales 11/13/2021 (Update flag status)
    PROCEDURE UPD_FLAG_STATUS(P_NAME VARCHAR2, P_NEW_STATUS VARCHAR2) IS
    BEGIN 
        UPDATE GAME_FLAGS SET STATUS=P_NEW_STATUS WHERE NAME = P_NAME;
        COMMIT;
    END UPD_FLAG_STATUS;

END GAME_FLAGS_PQ01;
