CREATE OR REPLACE PACKAGE BODY MAIN IS

    --jcanales 11/13/2021 (Start new game by asking for players names)
    PROCEDURE START_GAME_PLAYERS(P_NAME1 VARCHAR2, P_NAME2 VARCHAR2) IS
    BEGIN
        GAME_PQ01.INS_PLAYERS_NEW_GAME(P_NAME1, P_NAME2);
    END START_GAME_PLAYERS;
END MAIN;
/