BEGIN
  --PARA REINICIAR PARTIDA
  --DELETE PIECES_STATUS;

  --PIEZAS DE ABAJO O JUGADOR 1
  INSERT INTO PIECES_STATUS (CORD,PIEZA) VALUES('A2','P');
  INSERT INTO PIECES_STATUS (CORD,PIEZA) VALUES('B2','P');
  INSERT INTO PIECES_STATUS (CORD,PIEZA) VALUES('C2','P');
  INSERT INTO PIECES_STATUS (CORD,PIEZA) VALUES('D2','P');
  INSERT INTO PIECES_STATUS (CORD,PIEZA) VALUES('E2','P');
  INSERT INTO PIECES_STATUS (CORD,PIEZA) VALUES('F2','P');
  INSERT INTO PIECES_STATUS (CORD,PIEZA) VALUES('G2','P');


  --PIEZAS DE ARRIBA O JUGADOR 2
  INSERT INTO PIECES_STATUS (CORD,PIEZA) VALUES('A7','p');
  INSERT INTO PIECES_STATUS (CORD,PIEZA) VALUES('B7','p');
  INSERT INTO PIECES_STATUS (CORD,PIEZA) VALUES('C7','p');
  INSERT INTO PIECES_STATUS (CORD,PIEZA) VALUES('D7','p');
  INSERT INTO PIECES_STATUS (CORD,PIEZA) VALUES('E7','p');
  INSERT INTO PIECES_STATUS (CORD,PIEZA) VALUES('F7','p');
  INSERT INTO PIECES_STATUS (CORD,PIEZA) VALUES('G7','p');

END;
/