BEGIN
  INSERT INTO BOARD (FILA,COLUMNA) VALUES(1,'A');
INSERT INTO BOARD (COLUMNA,FILA) VALUES('A',2);
INSERT INTO BOARD (COLUMNA,FILA) VALUES('A',3);
INSERT INTO BOARD (COLUMNA,FILA) VALUES('A',4);
INSERT INTO BOARD (COLUMNA,FILA) VALUES('A',5);
INSERT INTO BOARD (COLUMNA,FILA) VALUES('A',6);
INSERT INTO BOARD (COLUMNA,FILA) VALUES('A',7);
INSERT INTO BOARD (COLUMNA,FILA) VALUES('A',8);

INSERT INTO BOARD (COLUMNA,FILA) VALUES('B',1);
INSERT INTO BOARD (FILA,COLUMNA) VALUES(2,'B');
INSERT INTO BOARD (COLUMNA,FILA) VALUES('B',3);
INSERT INTO BOARD (COLUMNA,FILA) VALUES('B',4);
INSERT INTO BOARD (COLUMNA,FILA) VALUES('B',5);
INSERT INTO BOARD (COLUMNA,FILA) VALUES('B',6);
INSERT INTO BOARD (COLUMNA,FILA) VALUES('B',7);
INSERT INTO BOARD (COLUMNA,FILA) VALUES('B',8);

INSERT INTO BOARD (COLUMNA,FILA) VALUES('C',1);
INSERT INTO BOARD (COLUMNA,FILA) VALUES('C',2);
INSERT INTO BOARD (FILA,COLUMNA) VALUES(3,'C');
INSERT INTO BOARD (COLUMNA,FILA) VALUES('C',4);
INSERT INTO BOARD (COLUMNA,FILA) VALUES('C',5);
INSERT INTO BOARD (COLUMNA,FILA) VALUES('C',6);
INSERT INTO BOARD (COLUMNA,FILA) VALUES('C',7);
INSERT INTO BOARD (COLUMNA,FILA) VALUES('C',8);

INSERT INTO BOARD (COLUMNA,FILA) VALUES('D',1);
INSERT INTO BOARD (COLUMNA,FILA) VALUES('D',2);
INSERT INTO BOARD (COLUMNA,FILA) VALUES('D',3);
INSERT INTO BOARD (FILA,COLUMNA) VALUES(4,'D');
INSERT INTO BOARD (COLUMNA,FILA) VALUES('D',5);
INSERT INTO BOARD (COLUMNA,FILA) VALUES('D',6);
INSERT INTO BOARD (COLUMNA,FILA) VALUES('D',7);
INSERT INTO BOARD (COLUMNA,FILA) VALUES('D',8);

INSERT INTO BOARD (COLUMNA,FILA) VALUES('E',1);
INSERT INTO BOARD (COLUMNA,FILA) VALUES('E',2);
INSERT INTO BOARD (COLUMNA,FILA) VALUES('E',3);
INSERT INTO BOARD (COLUMNA,FILA) VALUES('E',4);
INSERT INTO BOARD (FILA,COLUMNA) VALUES(5,'E');
INSERT INTO BOARD (COLUMNA,FILA) VALUES('E',6);
INSERT INTO BOARD (COLUMNA,FILA) VALUES('E',7);
INSERT INTO BOARD (COLUMNA,FILA) VALUES('E',8);

INSERT INTO BOARD (COLUMNA,FILA) VALUES('F',1);
INSERT INTO BOARD (COLUMNA,FILA) VALUES('F',2);
INSERT INTO BOARD (COLUMNA,FILA) VALUES('F',3);
INSERT INTO BOARD (COLUMNA,FILA) VALUES('F',4);
INSERT INTO BOARD (COLUMNA,FILA) VALUES('F',5);
INSERT INTO BOARD (FILA,COLUMNA) VALUES(6,'F');
INSERT INTO BOARD (COLUMNA,FILA) VALUES('F',7);
INSERT INTO BOARD (COLUMNA,FILA) VALUES('F',8);

INSERT INTO BOARD (COLUMNA,FILA) VALUES('G',1);
INSERT INTO BOARD (COLUMNA,FILA) VALUES('G',2);
INSERT INTO BOARD (COLUMNA,FILA) VALUES('G',3);
INSERT INTO BOARD (COLUMNA,FILA) VALUES('G',4);
INSERT INTO BOARD (COLUMNA,FILA) VALUES('G',5);
INSERT INTO BOARD (COLUMNA,FILA) VALUES('G',6);
INSERT INTO BOARD (FILA,COLUMNA) VALUES(7,'G');
INSERT INTO BOARD (COLUMNA,FILA) VALUES('G',8);

INSERT INTO BOARD (COLUMNA,FILA) VALUES('H',1);
INSERT INTO BOARD (COLUMNA,FILA) VALUES('H',2);
INSERT INTO BOARD (COLUMNA,FILA) VALUES('H',3);
INSERT INTO BOARD (COLUMNA,FILA) VALUES('H',4);
INSERT INTO BOARD (COLUMNA,FILA) VALUES('H',5);
INSERT INTO BOARD (COLUMNA,FILA) VALUES('H',6);
INSERT INTO BOARD (COLUMNA,FILA) VALUES('H',7);
INSERT INTO BOARD (FILA,COLUMNA) VALUES(8,'H');V

END;
/