BEGIN
    INSERT INTO BOARD(A) VALUES(' ');
    INSERT INTO BOARD(A) VALUES(' ');
    INSERT INTO BOARD(A) VALUES(' ');
    INSERT INTO BOARD(A) VALUES(' ');
    INSERT INTO BOARD(A) VALUES(' ');
    INSERT INTO BOARD(A) VALUES(' ');
    INSERT INTO BOARD(A) VALUES(' ');
    INSERT INTO BOARD(A) VALUES(' ');

END;
/